### ISSUE TITLE
Name Collisision

### ISSUE THREAD

**Issue by lswank** [valentinradu/Helm#2]
Helm is *also* the name of a core project in the Kubernetes world. It is a package manager for Kubernetes, and the packages are referred to as "Helm charts". Normally I'd say, "Hey, don't worry about it at all", but it's money coming from AWS, Google, Apple, MSFT, Cisco, ATT, Intel, Oracle, ARM, and even Alibaba and Huawei. (The Cloud Native Computing Foundation) When you have that many big names behind a single project, that is foundational to a lot of what those companies are doing in the cloud space, you can bet their legal teams will get bored and find your name eventually.

Just a heads up. I have had a few projects that flew under the radar until companies made me change them.

"Mobile Tetris" <- EA Games USA
"Mobile Finder" <- Apple

Just a thing to consider.

**Comment by valentinradu** [comment]
(Relatively many) Others have voiced this concern as well. I feel legally-wise there's no overlap and little reason to worry: it's a free, 50 stars, open-source library that has nothing to do with cloud computing and it's not competing with k8s Helm at any level, I doubt any of those big players care about it to even bother writing an email. In other words, if they'll contact me requesting to change the name, I will.

That being said, I'm more worried about people constantly complaining that "Helm is already taken bro" haha, which is true, I must admit. For this reason, I'm planning to change the name, I was thinking `HelmRouter` but I'm still thinking about it, maybe I find something better. Obviously any suggestions are welcomed!

**Comment by jasperblues** [comment]
I would say who cares about the name collision, chill out people! 

But for #random ideas maybe instead of Helms, Tillers & Captain Ahab related names, something to do with telephone switchboards could work? 

erm . . like: 

* Switchboard
* Magneto (the think you crank on a vintage telephone)
* Something to do with George Willard Croy (the world's first telphone switch operator)
* Call, bell, ring, buzz, tinkle, horn <-- Old slang words for telephone calls/routing 

--

Or maybe play on the graph nature: 

* Djikstra (invented shortest path algorithnm)
* Vertex
* Edge
* Euler (Euler? . . . Euler? . . . Euler? . . . Euler? . . . "HERE!")

**Comment by valentinradu** [comment]
I like Euler! Although not fully related with the routing part, who cares!
I need to check if there's an iOS/macOS library with that name (that's the only type of collision I do find important)

**Comment by jasperblues** [comment]
Its so hard to pick a unique name these days!

For what its worth I wrote a (crusty and old now) iOS/Mac lib called Typhoon, and the Kubernetes people co-opted that name https://github.com/poseidon/typhoon . .  So I'm sure we can all get along but if it comes to war, its not like they have the moral high ground :D
