### ISSUE TITLE
[Question] Going backwards w/ Stack Navigation 

### ISSUE THREAD

**Issue by jasperblues** [valentinradu/Helm#9]
With the Stack (list/detail) based navigation in the playground, it wasn't clear how to handle going back. 

I wired it up in a stand-alone app based on the Playground example, and put the following on the tail of the list view:

```
.onAppear {
  print("\n\nPresenting these frags: \(helm.presentedFragments)")
}
```

. . and noticed that after navigating back, the state was out of sync, according to my Helm the detail view was still being presented. So question . . . 

**Question:** Is there a pattern you had in mind for this? Just put `helmPresent()` in the `disappear` block of the detail view?

**Comment by valentinradu** [comment]
That's because how `NavigationLink` works. If you replace `Helm` with a regular `Bool` for `isActive`, you'll get the `Bool`'s value set to `true` in list's `onAppear` (although is it should be `false` since the detail view is not presented anymore. The idea is, `NavigationLink` sets its `isActive` binding to false only **after** `onAppear` (and the animation is finished). I'm not sure I fully understand your last question, but I'm going to close this as unrelated to the library. Feel free to comment below re the last Q.

**Comment by jasperblues** [comment]
The question was: "Is there a plan to address this quirk about how `NavigationLink` works in Helm, so that Helm's `presentedFragments` reflects reality? If yes, would (second question) a manual step (ie calling `helmPresent(parentFrag) in the disappear method of the detail view be reasonable)"? 

----

Apologies if the question wasn't considered as being related to Helm. I'm not very experienced with SwiftUI and don't know its quirks.

**Comment by valentinradu** [comment]
Ah, OK, got it. So:

1. Not possible to address it in Helm since the `NavigationLink` (which is not part of Helm) is holding the source of truth when dismissing the detail view. And that source of truth it set to `true` only _after_ the dismiss animation is complete, and after `didAppear` is called
2. That seems hackish, again, the source of truth here is not Helm, but the `NavigationLink` which controls `isActive` on dismiss. It might work, but might also cause issues, I don't know, never tried it.
3. A possible workaround is to receive updated directly from `$presentedFragments` using `.receive`, this will be called each time the fragments changes, regardless of the reason for which they do.
